[config]

[templates.eww]
input_path = 'colors-eww.scss'
output_path = '~/.config/ignis/colors.scss'
scheme = "dark"

[templates.pywalfox]
input_path = 'pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'
scheme = "dark"

[templates.waybar]
input_path = 'colors.css'
output_path = '~/.config/waybar/colors.css'
scheme = "dark"
post_hook = "pkill -USR1 swaync"

[templates.foot]
input_path = 'colors-foot.ini'
output_path = '~/.config/foot/colors.ini'
scheme = "dark"

[templates.alacritty]
input_path = 'colors.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.rofi]
input_path = 'rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.rofi_wallpaper]
input_path = 'rofi_wall.rasi'
output_path = '~/.config/cached/current_wall.rasi'

[templates.gtk3]
input_path = 'gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = 'gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.hyprland]
input_path = 'hypr-colrs.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.niri]
input_path = 'config.kdl'
output_path = '~/.config/niri/config.kdl'

[templates.fuzzel]
input_path = 'fuzzel'
output_path = '~/.config/fuzzel/fuzzel.ini'

[templates.quickshell]
input_path = 'qs.qml'
output_path = '~/.config/quickshell/colors.qml'

[templates.discord]
input_path = 'discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'


