#!/bin/bash
#autostart
nitrogen --restore &
dex -a -s ~/.config/autostart/ &
sxhkd &
setxkbmap -layout us,ru,il -option grp:alt_shift_toggle &
alacritty &
sleep 4 && polybar &

#BSPC configs
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width         2.2
bspc config window_gap          5
bspc config top_padding 28 
bspc config split_ratio          0.5
bspc config normal_border_color "#ffb4aa"
bspc config active_border_color "#dd352d"
bspc config focused_border_color "#dd352d"
bspc config presel_feedback_color "#000000"
bspc blur 8
bspc corner_radius 12
