#!/usr/bin/env sh

# scripts/force_push
REPO_NAME=NullDE
set -e

# Debug: Print variable values (excluding sensitive tokens)
echo "[+] REPO_OWNER: $REPO_OWNER"
echo "[+] REPO_NAME: $REPO_NAME"

# Fail early if variables are not set
[ -z "$REPO_OWNER" ] && { echo "REPO_OWNER not set"; exit 1; }
[ -z "$REPO_NAME" ] && { echo "REPO_NAME not set"; exit 1; }
[ -z "$ACCESS_GIT" ] && { echo "ACCESS_GIT not set"; exit 1; }

# Configure Git
echo "[+] Authorizing Git"
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"

# Add and commit changes
echo "[+] Adding and committing changes"
git add .
git commit -m "Upload latest packages to repository" || echo "No changes to commit"

# Force push to main
echo "[+] Force pushing to main"
git push -f "https://$REPO_OWNER:$ACCESS_GIT@github.com/$REPO_OWNER/$REPO_NAME.git" main
