[colors.primary]
background = '#0f150c'
foreground = '#dee5d6'
 
[colors.cursor]
text = '#dee5d6'
cursor = '#becab5' 
 
[colors.vi_mode_cursor]
text = '#0f150c'
cursor = '#74de56' 
 
[colors.search.matches]
foreground = '#3f4a39' 
background = '#5cd4ff' 
 
[colors.search.focused_match]
foreground = '#3f4a39' 
background = '#74de56' 
 
[colors.footer_bar]
foreground = '#3f4a39' 
background = '#dee5d6' 
 
[colors.hints.start]
foreground = '#3f4a39' 
background = '#a1d48c' 
 
[colors.hints.end]
foreground = '#3f4a39' 
background = '#a1d48c' 
 
[colors.selection]
text = '#0f150c'
background = '#74de56'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#74de56' 
yellow = '#176e00' 
blue = '#74de56' 
magenta = '#5cd4ff' 
cyan = '#a1d48c' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
