[colors.primary]
background = '#1e0f0e'
foreground = '#fadcd8'
 
[colors.cursor]
text = '#fadcd8'
cursor = '#e4beb9' 
 
[colors.vi_mode_cursor]
text = '#1e0f0e'
cursor = '#ffb4aa' 
 
[colors.search.matches]
foreground = '#5b403c' 
background = '#ffb961' 
 
[colors.search.focused_match]
foreground = '#5b403c' 
background = '#ffb4aa' 
 
[colors.footer_bar]
foreground = '#5b403c' 
background = '#fadcd8' 
 
[colors.hints.start]
foreground = '#5b403c' 
background = '#ffb4aa' 
 
[colors.hints.end]
foreground = '#5b403c' 
background = '#ffb4aa' 
 
[colors.selection]
text = '#1e0f0e'
background = '#ffb4aa'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb4aa' 
yellow = '#ba1918' 
blue = '#ffb4aa' 
magenta = '#ffb961' 
cyan = '#ffb4aa' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
