[display]
show_username = true
show_host = true
show_os = true
show_kernel = true
show_uptime = true
show_cpu = true
show_memory = true
show_gpu = false
show_shell = true
show_rust = true
show_disk = true
show_packages = true

[ascii]
art_style = "crab"  
color = "bright_cayan"  
art_width = 16

[format]
info_prefix = ">> "
info_color = "bright_white"
label_color = "bright_yellow"
title_color = "bright_magenta"
max_width = 0
separator = " :: "
