name: Auto-sync Hyprland Configs

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [sync-configs]

jobs:
  sync-configs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_GIT }}  # Use PAT for checkout

      - name: Run cleanup script
        run: |
          cd .config
          chmod +x cleanup_configs
          ./cleanup_configs

      - name: Force push
        env:
          ACCESS_GIT: ${{ secrets.ACCESS_GIT }}  # Use PAT here
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: NullDE
        run: |
          chmod +x scripts/force_push
          ./scripts/force_push
